include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Security
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    
    # Style
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    
    # Best Practices
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_interpolation_to_compose_strings: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    use_key_in_widget_constructors: true
    
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
